#!/bin/bash
# ============================================================================
# Generates the artifacts to import the repositories from the GitHub
# organization to Pulumi.
#
# USAGE:
#   import-org-to-pulumi
#
# REQUIREMENTS:
#   - curl
#   - jq
# ============================================================================

source /usr/bin/helpers.sh

ID=$(generate_id)
# shellcheck disable=2034
GITHUB_USER=""

ID=${ID} list-repositories
ID=${ID} get-repositories-data
ID=${ID} convert-repositories-to-resources

ID=${ID} list-members
ID=${ID} convert-members-to-resources

ID=${ID} list-teams
ID=${ID} get-teams-data
ID=${ID} convert-teams-to-resources
