#!/bin/bash
# ============================================================================
# Generates the artifacts to import the repositories from the GitHub account
# to Pulumi.
#
# USAGE:
#   import-repositories-to-pulumi
#
# REQUIREMENTS:
#   - curl
#   - jq
# ============================================================================

# shellcheck disable=SC1091
source /usr/bin/helpers.sh

ID=$(generate_id)
# shellcheck disable=2034
GITHUB_ORG=""

ID=${ID} list-repositories
ID=${ID} get-repositories-data
ID=${ID} convert-repositories-to-resources
