#!/bin/bash
# ============================================================================
# It will list all of the user's or organization's repositories.
# Generates the `list-repositories.json` file with all the repositories listed.
#
# USAGE:
#   list-repositories
#   ID="..." list-repositories
#
# REQUIREMENTS:
#   - curl
#   - jq
# ============================================================================

# shellcheck disable=SC1091
source /usr/bin/helpers.sh

ID=${ID:-''}
if [ -z "${ID}" ]; then
  ID=$(generate_id)
fi
ID_DIR=$(get_id_dir "$ID")
CMD_DIR="${ID_DIR}/list-repositories"
mkdir -p "${CMD_DIR}"
OUTPUT_FILE="${ID_DIR}/list-repositories.json"

GITHUB_ORG=${GITHUB_ORG:-''}
API_ENDPOINT="/user/repos?affiliation=owner&per_page=100&page="
if [ -n "${GITHUB_ORG}" ]; then
  API_ENDPOINT="/orgs/${GITHUB_ORG}/repos?per_page=100&page="
fi

printf "\n[%s] Starting to list repositories...\n" "${ID}"

get_all_resources "${API_ENDPOINT}" "${CMD_DIR}"
merge_all_files_into_one "${CMD_DIR}" "${OUTPUT_FILE}"
